"use client";

import { useState } from "react";
import { Check, Copy, Download, Loader2, Sparkles } from "lucide-react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import type { AgentDef } from "@/lib/agents/registry";

export function AgentRunner({ agent }: { agent: Pick<AgentDef, "id" | "name" | "inputMode" | "inputLabel" | "inputPlaceholder" | "runLabel"> }) {
  const [input, setInput] = useState("");
  const [running, setRunning] = useState(false);
  const [output, setOutput] = useState<string | null>(null);
  const [model, setModel] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const torRequired = agent.inputMode === "tor";
  const canRun = !running && (!torRequired || input.trim().length > 0);

  async function run() {
    setRunning(true);
    setOutput(null);
    setModel(null);
    try {
      const res = await fetch(`/api/agents/${agent.id}/run`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ input }),
      });
      const data = await res.json();
      if (!res.ok) {
        toast.error(data.error ?? "The agent run failed.");
        return;
      }
      setOutput(data.text ?? "");
      setModel(data.model ?? null);
    } catch {
      toast.error("Could not reach the server. Check your connection and try again.");
    } finally {
      setRunning(false);
    }
  }

  async function copy() {
    if (!output) return;
    await navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  function download() {
    if (!output) return;
    const blob = new Blob([output], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${agent.id}-${new Date().toISOString().slice(0, 10)}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="space-y-6">
      <div className="space-y-2">
        <Label htmlFor="agent-input">{agent.inputLabel}</Label>
        <Textarea
          id="agent-input"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder={agent.inputPlaceholder}
          rows={agent.inputMode === "tor" ? 12 : 4}
          disabled={running}
        />
      </div>

      <div className="flex items-center gap-3">
        <Button onClick={run} disabled={!canRun}>
          {running ? (
            <>
              <Loader2 className="size-4 animate-spin" /> Working…
            </>
          ) : (
            <>
              <Sparkles className="size-4" /> {agent.runLabel}
            </>
          )}
        </Button>
        {running && (
          <p className="text-sm text-muted-foreground">
            This can take a minute or two — the agent is reasoning over DC&A Hub&apos;s references.
          </p>
        )}
      </div>

      {output !== null && (
        <div className="rounded-xl border bg-card">
          <div className="flex items-center justify-between gap-3 border-b border-border/60 px-5 py-3">
            <div className="min-w-0">
              <p className="font-heading text-sm font-semibold">Draft (first draft for expert review)</p>
              {model && (
                <p className="truncate text-xs text-muted-foreground">Generated by {model}</p>
              )}
            </div>
            <div className="flex shrink-0 items-center gap-2">
              <Button variant="outline" size="sm" onClick={copy}>
                {copied ? <Check className="size-3.5" /> : <Copy className="size-3.5" />}
                {copied ? "Copied" : "Copy"}
              </Button>
              <Button variant="outline" size="sm" onClick={download}>
                <Download className="size-3.5" /> Download .md
              </Button>
            </div>
          </div>
          <pre className="max-h-[60vh] overflow-auto whitespace-pre-wrap px-5 py-4 font-sans text-sm leading-relaxed text-foreground">
            {output || "(The agent returned an empty response.)"}
          </pre>
        </div>
      )}
    </div>
  );
}
